import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = path.join(root, 'dist');
await fs.rm(output, { recursive: true, force: true });
await fs.mkdir(output, { recursive: true });
await fs.cp(path.join(root, 'web'), output, { recursive: true });
await fs.cp(path.join(root, 'data'), path.join(output, 'data'), { recursive: true });
console.log('Built static site in dist/ from web/ and data/.');
